### ISSUE TITLE
Cardian bot can't find the cards.

### ISSUE THREAD

**Issue by TeaJayed** [okkdev/cardian#1]
The bot isn't able to find any cards, doesnt auto-fill and even manually typing out the cards name doesn't help.

**Comment by okkdev** [comment]
Thanks for the report. 
Seems like there is some bug in the Nostrum Discord library which caused a crash, which wouldn't be a problem but Cardian then failed to fetch the cards and rescheduled it in 2hours. I should probably have Cardian retry sooner if the card cache is empty. 😅 
I restarted Cardian and it was able to fetch the cards successfully. 👍🏻
