### ISSUE TITLE
Searching "Very Fun Dragon" in /art and /card won't work

### ISSUE THREAD

**Issue by eyal282** [okkdev/cardian#2]
I think you should urgently fix it.

**Comment by okkdev** [comment]
I might have an idea how to add search aliases.
Are there any other cards that should have alternative names when searching?

**Comment by okkdev** [comment]
Alright it works. Now to collect some other aliases.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/20144629/180239545-3a0a9d74-f724-4456-b719-9c73896f3680.png">

**Comment by eyal282** [comment]
> Alright it works. Now to collect some other aliases. <img alt="image" width="280" src="https://user-images.githubusercontent.com/20144629/180239545-3a0a9d74-f724-4456-b719-9c73896f3680.png">

I'm on the server of Master Duel, I don't see it working.

**Comment by okkdev** [comment]
Yeah sorry, I haven't pushed it yet. I'm on vacation. I'll do it in a week :)

**Comment by eyal282** [comment]
> Yeah sorry, I haven't pushed it yet. I'm on vacation. I'll do it in a week :)

Don't forget V.F.D ( Original OCG name IIRC )

And VFD

**Comment by okkdev** [comment]
Added in commit ebe62054888b7fa8ffd0b9202aff4fb397a92f8e and published in release [5.1](https://github.com/okkdev/cardian/releases/tag/5.1)
It should be live now, thanks for waiting! :)
