### ISSUE TITLE
Bot cannot display any image after searching.

### ISSUE THREAD

**Issue by EzeMc13** [okkdev/cardian#4]
The Cardian bot added to the Master Duel Meta Discord server is unable to show the art of any card after searching for it, it only shows the name but not the image of said card.

**Comment by okkdev** [comment]
thanks for the issue, unfortunately it's a discord problem. We'll have to wait till they fix it on their end :(
https://github.com/discord/discord-api-docs/issues/6171

**Comment by okkdev** [comment]
Discord has resolved the issue :)
