### ISSUE TITLE
Bot's slash commands currently non-functional in multiple servers

### ISSUE THREAD

**Issue by Ocean0000000** [okkdev/cardian#5]
/card and /art are both not working in multiple servers. Cardian bot does not respond to the slash commands.

**Comment by Ocean0000000** [comment]
Autocomplete is also non-functional

**Comment by okkdev** [comment]
Thank you so much for the report. Seems like something changed on Discord's side which broke the Discord library I'm using. https://github.com/Kraigie/nostrum/issues/523
I'll try to fix it asap.

**Comment by okkdev** [comment]
Seems like Discord switched from http2 to http1. Switched to Nostrum master and the bot should be back online shortly. 🙏🏻
